### ISSUE TITLE
Any chance we're getting support for Xperia U?

### ISSUE THREAD

**Issue by VictorQueiroz** [MediaDeb/MediaDeb#3] opened 2018-06-11 03:50 UTC
I have this old phone and I'd like to install Linux and use it as a Raspberry Pi. Model is Sony Xperia U ST25i. Any chance?

**Comment by nekromant** [comment] 2018-06-11 09:17
@VictorQueiroz unless you're feeling adventurous and are up for porting MediaDeb to NovaThor U8500 that resides inside the model you've mentioned - it ain't gonna happen. I don't have the hardware, haven't seen so far any kernel kitchen for it. And worst I'm really busy right now with that stuff called "real life" (tm) ;)  

So far you can give it a try and see if you can compile a working kernel and boot debian rootfs on the device. If you get that stuff working, we can see how to integrate the device support to the MediaDeb buildsystem.

**Comment by nekromant** [comment] 2018-06-12 11:45
I'm closing the issue for now, since it's not a bug of MediaDeb right now. If you're up to kernel hackery, feel free to reopen.

**Closed as completed by nekromant** 2018-06-12 11:45 UTC
Labels: help wanted, question
